version: '3.8'

services:
  app:
    image: moonputa/whatsapp-ai:latest
    container_name: whatsapp-ai
    ports:
      - '3000:3000'
    environment:
      - GROUP_NAME=${GROUP_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_credentials_secret
      - TAVILY_API_KEY=${TAVILY_API_KEY}

    volumes:
      - ./public:/app/public
      - ./session_data:/app/src/clients/session_data
      
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      